### ISSUE TITLE
🍕 Improve Listing Quality

### ISSUE THREAD

**Issue by danielsvitols** [PhysicalAddons/store-pages#9]
## Requirements

1. Speed is acceptable for good UX experiance 
2. `PCO` improved images (mars) and gifs
3. `POW` improved images and gifs
4. `PSA` style improvements
5. Fast Sale setup workflow

## Tasks

- [ ]  Speed optimisation
- [ ]  PCO media
- [ ]  POW media
- [ ]  PSA styling
- [x]  Sale workflow

## Acceptance criteria

- [ ] `PCO` Across listing represent different planets in images (Mars)
- [ ] `PCO` Video/gif that allows to understand addon
- [ ] `PSA` Match PSA style with rest of listings
- [ ] `POW` Video/Gif composition and lenght
- [ ] UX experiance is fast and pleasent
- [ ] Listing assets are optimized based on industry standarts
- [x] Fast workflow to setup new Sale in listings

**Comment by karlisup** [comment]
### Translation to Developer 
 1. New assets and manipulations with them:
 - PCO Across listing represent different planets in images (Mars)
 - PCO Video/gif that allows to understand addon
-  POW Video/Gif composition and length
 
 2. `webm` with `mp4` fallback in the right sizes using gulp automaton from a folder with all the assets.
 - UX experiance is fast and pleasant
 - Listing assets are optimized based on industry standards
 
3. Fix pricing `.scss` in PSA so it matches the rest.
- PSA Match PSA style with rest of listings

4. Fast workflow to setup new Sale in listings
a) check how git submodules could work for Netlify.
b) should we migrate to PCO system?
.. finish on Wednesday
